language: generic
services:
  - docker

before_install:
  - docker build -t lcartwri/web-demo-app .

#script:
 # - docker run lcartwri/web-demo-app

after_success:
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lcartwri/web-demo-app
  # Set your identification.
  - git config --global user.email "lcartwri@cisco.com"
  - git config --global user.name "lcartwri" 
  # Clone some repository you want into "repo" subfolder.
  - git clone https://lcartwri:${GH_TOKEN}@github.com/web-demo-code.git ./repo 
  # Now, perform your custom actions. Custom repository is cloned int "repo" subfolder of PWD.

  # After your actions are done, you might want to commit and push your changes.
  - cd repo
  - git commit -m "Actions done."
  - git push