language: generic
services:
  - docker
env:
  global:
  - USER="lcartwri"
  - EMAIL="lcartwri@cisco.com"
  - REPO="web-demo-deploy"
  - FILES="Dockerfile"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  - SHA=$(git rev-parse HEAD)

before_install:
  - docker build -t lcartwri/web-demo-app:$SHA .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install kustomize

after_success:
  - docker push lcartwri/web-demo-app:$SHA
  - git clone https://$GH_REPO
  - cd ./${REPO} && kustomize edit set image lcartwri/web-demo-app:$SHA
  - git commit -am 'Publish new version' 
  - - git push "https://${GH_TOKEN}@${GH_REPO}"

#deploy:
 # provider: script
  #script: bash ./deploy.sh
  #on:
   # all_branches: true