language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lcartwri/web-demo-app .

script:
  - docker run lcartwri/web-demo-app

after_success:
  - docker push -t lcartwri/web-demo-app