language: generic
services:
  - docker
env:
  global:
  - USER="lcartwri"
  - EMAIL="lcartwri@cisco.com"
  - REPO="web-demo-code"
  - FILES="Dockerfile"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  - SHA=$(git rev-parse HEAD)

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t lcartwri/web-demo-app .

#script:
 # - docker run lcartwri/web-demo-app


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    all_branches: true