language: generic
services:
  - docker
env:
  global:
  - USER="lcartwri"
  - EMAIL="lcartwri@cisco.com"
  - REPO="web-demo-code"
  - FILES="Dockerfile"
  - GH_REPO="github.com/${USER}/${REPO}.git"
  - SHA=$(git rev-parse HEAD)

before_install:
  #- docker build -t lcartwri/web-demo-app .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - sudo apt update
  - sudo apt install snapd
  - sudo snap install kustomize

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    all_branches: true